### ISSUE TITLE
NameError: name 'ZotCite' not defined

### ISSUE THREAD

**Issue by anandkumar89** [jalvesaq/cmp-zotcite#3]
I'm getting this error as soon as autocompletion starts - 
![Screenshot 2024-03-21 at 2 00 48 AM](https://github.com/jalvesaq/cmp-zotcite/assets/12571250/14d5f3af-d23a-4e2a-9669-ed9215986c9e)

Also, would it be possible to make it work with `coc-nvim`?

**Comment by jalvesaq** [comment]
What is the output of `:Zinfo`?

**Comment by jalvesaq** [comment]
> Also, would it be possible to make it work with coc-nvim?

Yes, if someone creates a source for it.

**Comment by jalvesaq** [comment]
> Zinfo returns nothing.

Make sure that Python is working correctly in Neovim. Run `:checkhealth`.

**Comment by jalvesaq** [comment]
Note zotcite is available only for Markdown, Rmd, and Quarto. You should run `:Zinfo` in one of these file types.

**Comment by jalvesaq** [comment]
Probably, you should take care of this:

```
- Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
```

Also, you are trying to run `coc.nvim` and `nvim-cmp` simultaneously. I think you should choose one of them.

**Comment by jalvesaq** [comment]
You can use `grep` to search for `htmlcomplete#CompleteTags` in Neovim' runtime directory and in the directory where your plugins are installed.

**Comment by jalvesaq** [comment]
> It could be possible to force cmp completion as done in obsidian.nvim which requires cmp and adds source from within the plugin.

It makes sense because I develop both `zotcite` and `cmp-zotcite`.

**Comment by raffaem** [comment]
FWIW, I got this error too and the problem was that I failed to call the `setup()` function of zotcite when initializing it

**Comment by jalvesaq** [comment]
> note: It could be possible to force cmp completion as done in obsidian.nvim which requires cmp and adds source from within the plugin.

This will no longer be necessary when I merge the branch https://github.com/jalvesaq/zotcite/tree/improve_seeker because it will be possible to use Telescope to insert a citation key, with the advantage of being possible to filter the results with multiple keywords.

**Comment by jalvesaq** [comment]
> FWIW, I got this error too and the problem was that I failed to call the setup() function of zotcite when initializing it

Thanks for the feedback! I will add the information that the setup function is required to zotcite's README.
